FROM metabrainz/python:2.7

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
                       build-essential \
                       ca-certificates \
                       cron \
                       git \
                       libpq-dev \
                       libffi-dev \
                       libssl-dev \
                       libxml2-dev \
                       libxslt1-dev \
                       pxz \
                       ipython \
    && rm -rf /var/lib/apt/lists/*

# PostgreSQL client
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
ENV PG_MAJOR 9.5
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
RUN apt-get update \
    && apt-get install -y postgresql-client-$PG_MAJOR \
    && rm -rf /var/lib/apt/lists/*

# Dockerize
ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# PostgreSQL password
ENV PGPASSWORD "acousticbrainz"

# Node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

RUN mkdir /code
WORKDIR /code

# Python dependencies
COPY requirements.txt /code/requirements.txt
RUN mkdir /code/docs/
COPY docs/requirements.txt /code/docs/requirements.txt
RUN pip install -r requirements.txt

COPY . /code/
CMD python manage.py runserver
